### ISSUE TITLE
Establecer el Logo de Lima

### ISSUE THREAD

**Issue by bertocq** [LimaDecide/consul#1]
Usar los logos de la Municipalidad de Lima en la aplicación (en sustitución de los logos genéricos de CONSUL)

- https://user-images.githubusercontent.com/983242/37673159-d1ba95ee-2c6f-11e8-97cf-068ddbe0bade.png
- https://user-images.githubusercontent.com/983242/37673161-d25d958c-2c6f-11e8-9923-c431188f6797.png

**Comment by voodoorai2000** [comment]
Done from the admin interface
