### ISSUE TITLE
Cambiar el mapa de la ciudad

### ISSUE THREAD

**Issue by bertocq** [LimaDecide/consul#12]
Es necesario una imagen del mapa de la ciudad con los diferentes distritos resaltados y nombrados para sustituir a la imagen de https://github.com/LimaDecide/consul/blob/master/app/assets/images/map.jpg

Un ejemplo puede ser el mapa usado por Madrid https://github.com/AyuntamientoMadrid/consul/blob/master/app/assets/images/map.jpg

**Comment by bertocq** [comment]
![plano-lima-metropolitana](https://user-images.githubusercontent.com/983242/37797313-bdb4ec7e-2e19-11e8-8736-d133fbeae652.jpg)

**Comment by csimonl74** [comment]
Hola @bertocq en decidelima.munlima.gob.pe sigue sin incorporarse este mapa que fue proporcionado en marzo. Sigue saliendo el mapa por defecto con el texto "Replace with your city map". Por favor, podrías revisarlo. Gracias.

**Comment by bertocq** [comment]
Hola @csimonl74 podeis hacerlo vosotros mismos, esta explicado en la documentación https://consul_docs.gitbooks.io/docs/content/es/customization/images.html
